openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger service-systemic-showcase
  description: Documentation for service-systemic-showcase synchronous api
  termsOfService: http://swagger.io/terms/
  contact:
    name: author
    email: author@domain.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

paths:
  /__/manifest:
    get:
      tags:
        - Admin
      description: Returns the service manifest file
      operationId: manifest
      responses:
        '200':
          description: manifest response
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/EmptyManifest'
                  - $ref: '#/components/schemas/Manifest'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/message/{id}:
    get:
      tags:
        - Api
      description: Returns the message v1
      operationId: messageV1
      parameters:
        - name: id
          in: path
          description: id of the message
          required: true
          schema:
            type: string
      responses:
        '200':
          description: message v1 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageV1'
        '404':
          description: message v1 not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v2/message/{id}:
    get:
      tags:
        - Api
      description: Returns the message v2
      operationId: messageV2
      parameters:
        - name: id
          in: path
          description: id of the message
          required: true
          schema:
            type: string
      responses:
        '200':
          description: message v2 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageV2'
        '404':
          description: message v2 not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    EmptyManifest:
      type: object
      minProperties: 0
      maxProperties: 0

    Manifest:
      type: object
      required:
        - name
        - version
        - timestamp
        - scm
      properties:
        name:
          type: string
        version:
          type: string
        timestamp:
          type: string
        scm:
          type: object
          required:
            - remote
            - branch
            - commit
          properties:
            remote:
              type: string
            branch:
              type: string
            commit:
              type: string
              
    MessageV1:
      type: object
      required:
        - id
        - text
      properties:
        id:
          type: string
        text:
          type: string

    MessageV2:
      type: object
      required:
        - id
        - text
        - receptionTimestamp
      properties:
        id:
          type: string
        text:
          type: string
        receptionTimestamp:
          type: string
          
    NotFoundError:
      type: object
      required:
        - code
        - message
        - extra
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        extra:
          type: string
          
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string